name: PHP Install and Test 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest    
    

    steps:
    - name: Setup PHP with PECL extension
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'        
          
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock      
      run: composer validate
  
    - name: Cache Composer packages   
      id: composer-cache
      uses: actions/cache@v2
      with:            
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
    
    - name: Composer Install
      if: steps.composer-cache.outputs.cache-hit != 'true'            
      run: composer install --prefer-dist --no-progress --no-suggest
  
 
    #PHPStan Static Code Analysis 
    - name: PHPStan      
      continue-on-error: true
      run: vendor/bin/phpstan analyse --ansi   
      
    #Run PHPUnit Tests 
    - name: PHPUnit Tests      
      continue-on-error: false
      run: ./vendor/bin/phpunit
